# Generated by Django 2.1.15 on 2020-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200105_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondary_language',
            field=models.ManyToManyField(related_name='secondary_language', to='core.Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='tertiary_language',
            field=models.ManyToManyField(related_name='tertiary_language', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_language',
            field=models.ManyToManyField(related_name='primary_language', to='core.Language'),
        ),
    ]
